TARGET_BCM2708_COMPILE_RAZDROID_LIBS := 
ifeq ($(strip $(TARGET_BCM2708_COMPILE_RAZDROID_LIBS)),)

# Gralloc
PRODUCT_PACKAGES += gralloc.bcm2708 libdispmanx

# HWComposer
PRODUCT_PACKAGES += \
	hwcomposer.bcm2708

TARGET_HWC_VERSION := 1_0

TARGET_LOG_VIDEOCORE := true
TARGET_LOG_EGL := true
endif
