LOCAL_CFLAGS :=-DUSE_VCHIQ_ARM -DVCHI_BULK_ALIGN=1 -DVCHI_BULK_GRANULARITY=1 \
				-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
				-DEGL_SERVER_DISPMANX -DGL_GLEXT_PROTOTYPES -DGL_EGLEXT_PROTOTYPES \
				-DKHRN_BCG_ANDROID -DKHRN_COMMAND_MODE_DISPLAY -Wno-missing-field-initializers
