LOCAL_CFLAGS :=-DUSE_VCHIQ_ARM -DVCHI_BULK_ALIGN=1 -DVCHI_BULK_GRANULARITY=1 \
				-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
				-DEGL_SERVER_DISPMANX -DEGL_EGLEXT_ANDROID_STRUCT_HEADER
