LOCAL_CFLAGS :=-DUSE_VCHIQ_ARM -DVCHI_BULK_ALIGN=1 -DVCHI_BULK_GRANULARITY=1 \
				-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
				-DGL_GLEXT_PROTOTYPES -DGL_EGLEXT_PROTOTYPES \
				-Wno-missing-field-initializers
